# C:\Program Files\SplunkUniversalForwarder\etc\system\local\inputs.conf
# This configuration forces the Splunk Universal Forwarder to ingest high-fidelity Sysmon logs.

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main
renderXml = true
